SMALL_RADIUS_SIZE = 56
MED_RADIUS_SIZE = 170
BIG_RADIUS_SIZE = 240
AVERAGE_CENTER = (320, 246)
IMG_DIMENSION_W = 640  # No modificar, la red neuronal se entreno con estos valores
IMG_DIMENSION_H = 480  # No modificar, la red neuronal se entreno con estos valores
OUTPUT_IMG_DIMENSION = 512
PARAM1_HOUGH = 173
PARAM2_HOUGH = 23
CIRCLE_PERC_FILTER = 0.7
